#!/usr/bin/python

import os

Import('env')

env = env.Clone()

env.Append(LIBS=['backend'], LIBPATH=['..'],
        RPATH=env.Literal(os.path.join('\\$$ORIGIN', os.pardir)))

for i in Glob('*.cpp')+Glob('*.c'):
    if i.name=='elfsh.c':
        env.Program(target='elfsh',
                source=[i],
                CPPDEFINES=['ERESI64'])
        continue
    #else
    env.Program(target=i.name.rsplit('.', 1)[0],
            source=[i])
