#!/usr/bin/python

import os

Import('qtEnv')

env = qtEnv.Clone()

env.EnableQt4Modules([
    'QtGui',
    'QtCore'
    ])

env.Append(LIBS=['dl'])
env.Append(CPPPATH=['#'],
        LIBS=['backend'], LIBPATH=[Dir('../backend').abspath],
        RPATH=env.Literal(os.path.join('\\$$ORIGIN', os.pardir, 'lib')))
env.Append(LINKFLAGS=['-rdynamic'])

env.Moc4('mainwindow.h')
env.Moc4('Plugin.h')

# env.Uic4(Glob('*.ui'))
frontendTarget = env.Program('mainwindow', source=Glob('*.cpp')+Glob('*.cc'))
Install(env['LOCAL_BINDIR'], frontendTarget)
