#!/usr/bin/python

import os

Import('qtEnv')

env = qtEnv.Clone()

env.EnableQt4Modules([
    'QtGui',
    'QtCore'
    ])

env.Append(LIBS=['dl'])
env.Append(CPPPATH=['#'],
        LIBS=['backend'], LIBPATH=[Dir('../backend').abspath],
        RPATH=env.Literal(os.path.join('\\$$ORIGIN', os.pardir, 'backend')))

# env.Uic4(Glob('*.ui'))
env.Program('mainwindow', source=Glob('*.cpp'))
