#!/usr/bin/python

Import('qtEnv')

env = qtEnv.Clone()

env.EnableQt4Modules([
    'QtGui',
    'QtCore'
    ])

env.Append(LIBS=['dl'])

# env.Uic4(Glob('*.ui'))
env.Program('mainwindow', source=Glob('*.cpp'))
