#!/usr/bin/python

Import('baseEnv qtEnv')

baseEnv = baseEnv.Clone()
qtEnv = qtEnv.Clone()

qtEnv.EnableQt4Modules([
    'QtGui',
    'QtCore'
    ])

qtEnv.Moc4('ui_MainWindow.h')
qtEnv.Moc4('MainWindow.h')

pluginTarget = qtEnv.SharedLibrary(target='ar', source=Glob('*.cpp')+Glob('*.cc'))
Install(qtEnv['LOCAL_DATADIR'], pluginTarget)
