language: cpp
compiler:
    - gcc
    - clang
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libc6-dev libqt4-dev libqt4-core libqt4-gui binutils binutils-dev libcppunit-dev clang-3.4
    - wget http://kamijou.info/elfutils_0.161-1_amd64.deb
    - sudo dpkg -i elfutils_0.161-1_amd64.deb
script: python2 vendor/scons.py && python2 vendor/scons.py test
