language: cpp
compiler:
    - gcc
    - clang
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libc6-dev elfutils libelf1 libelf-dev libqt4-dev libqt4-core libqt4-gui binutils binutils-dev libcppunit-dev
script: python2 vendor/scons.py && python2 vendor/scons.py test
