#!/usr/bin/python

Import('qtEnv')

env = qtEnv.Clone()

env.Append(LIBS=['elf', 'elfsh64'])

env.EnableQt4Modules([
    'QtCore'
    ])

env.Moc4('File.h')
env.Moc4('Backend.h')

env.SharedLibrary(target='backend', source=Glob('*.cpp')+Glob('*.c')+Glob('*.cc'))

Export('env')

SConscript('test/SConscript', duplicate=1)
