#!/usr/bin/python

Import('qtEnv')

env = qtEnv.Clone()

conf = Configure(env)
if not conf.CheckHeader('libelf.h') or not conf.CheckHeader('gelf.h') or not conf.CheckLib('elf'):
    print 'libelf not found!'
    Exit(1)
env = conf.Finish()

env.Append(LIBS=['elf'])

env.EnableQt4Modules([
    'QtCore'
    ])

env.Moc4('File.h')
env.Moc4('Backend.h')

libbackend = env.SharedLibrary(target='backend', source=Glob('*.cpp')+Glob('*.c')+Glob('*.cc'))
Install(env['LOCAL_LIBDIR'], libbackend)

Export('env')

SConscript('test/SConscript', duplicate=1)
