#!/usr/bin/python

Import('baseEnv qtEnv')

baseEnv = baseEnv.Clone()
qtEnv = qtEnv.Clone()

qtEnv.EnableQt4Modules([
    'QtGui',
    'QtCore'
    ])

expandTar = qtEnv.ExpandDefine('TypeDefines.h', 'TypeDefines.compact.h')
AlwaysBuild(expandTar)

pluginTarget = qtEnv.SharedLibrary(target='dyn', source=Glob('*.cpp')+Glob('*.cc'))
Install(qtEnv['LOCAL_DATADIR'], pluginTarget)
