#!/usr/bin/python

Import('qtEnv baseEnv')

qtEnv = qtEnv.Clone()
baseEnv = baseEnv.Clone()

qtEnv.EnableQt4Modules([
    'QtGui',
    'QtCore'
    ])

qtEnv.SharedLibrary(target='basic', source=Glob('*.cpp'))
