#!/usr/bin/python

import os

srcpath = Dir('.').srcnode().abspath

for i in os.listdir(srcpath):
    if not os.path.isdir(os.path.join(srcpath, i)):
        continue
    SConscript(os.path.join(i, 'SConscript'), duplicate=1)
