#!/usr/bin/python

import os

Import('baseEnv qtEnv')

baseEnv.Append(CPPPATH=['#backend'], LIBS=['backend'],
        LIBPATH=[Dir('../backend/').abspath])
qtEnv.Append(CPPPATH=['#', '#frontend'])

srcpath = Dir('.').srcnode().abspath

for i in os.listdir(srcpath):
    if not os.path.isdir(os.path.join(srcpath, i)):
        continue
    SConscript(os.path.join(i, 'SConscript'), duplicate=1)
