BINARY_PLUGIN_VALUE_TYPE, int
BINARY_PLUGIN_NAMESPACE, plugin_framework
BINARY_PLUGIN_OBJECTNAME, defines_ELFCLASS

ELFCLASSNONE, "Invalid class"
ELFCLASS32, "32-bit objects"
ELFCLASS64, "64-bit objects"
/* ELFCLASSNUM	3 */
